### ISSUE TITLE
Cannot redefine property: webdriver

### ISSUE THREAD

**Issue by evgenysushko** [cita-bot/cita-bot#13]
OS: macOS Catalina 10.15.6
Chrome:  88.0.4324.182

While running any of 3 scripts, I get the following error:

Traceback (most recent call last):
  File "example2.py", line 36, in <module>
    try_cita(context=customer, cycles=200)  # Try 200 times
  File "/Users/mac/Desktop/Projects/cita-bot/bcncita/cita.py", line 245, in try_cita
    driver = init_wedriver(context)
  File "/Users/mac/Desktop/Projects/cita-bot/bcncita/cita.py", line 197, in init_wedriver
    browser = init_chrome(context)
  File "/Users/mac/Desktop/Projects/cita-bot/bcncita/cita.py", line 238, in init_chrome
    browser.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
  File "/Users/mac/Desktop/Projects/cita-bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/mac/Desktop/Projects/cita-bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/Projects/cita-bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot redefine property: webdriver
  (Session info: chrome=88.0.4324.182)

**Comment by CloudNine13** [comment]
I've got the same issue, the first google search and StackOverflow didn't resolve the problem.

**Comment by CloudNine13** [comment]
@cita-bot for sure, but it works if you have the last update of Chrome (I had problems with the newest version of chromedriver), because the last version of chromedriver is not compatible with the version of Chrome I had (I think it was the last one because I tried to update it from settings). Probably the last version of chromedriver is ok for beta versions of Chrome, or for Chromium but I did not check it, so I cannot tell you for sure.
