### ISSUE TITLE
issue with telegram and feature request

### ISSUE THREAD

**Issue by DiegoMaK** [cita-bot/cita-bot#15]
Amazing! thanks for share.

I have an error, a good idea is to put a bool value to enable or disable the Telegram bot.
SOmething similar to the 
    auto_captcha=False, but for use_telegram=False.

The error that is appearing me is  in the telegram bot  .probably I can solve setting the telegram bot, But I don't need that .(At the end the detail error:)

IN ADDITION: To request this options to be included:
In Barcelona as you already have and in any office is OK, as you already have.

POLICIA- CARTA DE  INVITACION --> that is the one that I really need, I i found this bot , because is impossible schedule one appointment.
--> Here is this option, only appears DNI and passport, I need to use passport, because NIE is not an available option.

and if you can , with less priority also this one.(This one can be very useful for the community because is an option to request any kind of certificates.
POLICIA-CERTIFICADOS Y ASIGNACION NIE(NO COMUNITARIOS)

python3 /Users/MEDLI/github/cita-bot/grab_me.py
Traceback (most recent call last):
  File "/Users/MEDLI/github/cita-bot/grab_me.py", line 36, in <module>
    try_cita(context=customer, cycles=200)  # Try 200 times
  File "/Users/MEDLI/github/cita-bot/bcncita/cita.py", line 250, in try_cita
    context.updater = Updater(token=context.telegram_token, use_context=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/telegram/ext/updater.py", line 159, in __init__
    self.bot = Bot(token,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/telegram/bot.py", line 130, in __init__
    self.token = self._validate_token(token)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/telegram/bot.py", line 193, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

**Comment by DiegoMaK** [comment]
Hi , I already edit the code, I guess will work.

I didn't develop since 10 years ago, and not in python also, but was a good exercise go thought your code and add the "CARTA DE INVITACION "code, also the bool for telegram and avoid the error.


I'm testing, once I got the appointment and completely checked the code, I can share.

For the moment, I guess that the office selection is not working(becase I will never know in which one i will find an appointment, I put other alarm in this step, because until now I never found an appointment in this step...


Just partially working, but you idea was amazing :)
